// frontend/react/miniTalk/src/components/MessageInput.tsx
import { useState, useRef, useEffect } from 'react';
import { PaperAirplaneIcon, ExclamationTriangleIcon, FireIcon } from '@heroicons/react/24/outline';
import type { MessageType } from '../types';
import { MessageTypeLabels, MessageColors } from '../types';

interface MessageInputProps {
  onSendMessage: (content: string, type: MessageType) => void;
  onTyping: () => void;
  onStopTyping: () => void;
  disabled?: boolean;
}

export function MessageInput({ onSendMessage, onTyping, onStopTyping, disabled = false }: MessageInputProps) {
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState<MessageType>('normal');
  const [isTyping, setIsTyping] = useState(false);
  const [showTypePicker, setShowTypePicker] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const typingTimeoutRef = useRef<number | null>(null);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 120)}px`;
    }
  }, [message]);

  const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const value = e.target.value;
    if (value.length <= 500) {
      setMessage(value);
      
      // Handle typing indicators
      if (value.trim() && !isTyping) {
        setIsTyping(true);
        onTyping();
      }

      // Clear existing timeout
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }

      // Set new timeout to stop typing indicator
      typingTimeoutRef.current = setTimeout(() => {
        setIsTyping(false);
        onStopTyping();
      }, 1000) as unknown as number;
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const trimmedMessage = message.trim();
    if (!trimmedMessage || disabled) return;

    onSendMessage(trimmedMessage, messageType);
    setMessage('');
    setMessageType('normal');
    setShowTypePicker(false);
    
    // Stop typing indicator
    if (isTyping) {
      setIsTyping(false);
      onStopTyping();
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }
    }

    // Focus back to input
    textareaRef.current?.focus();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  const getTypeIcon = (type: MessageType) => {
    switch (type) {
      case 'important':
        return <ExclamationTriangleIcon className="w-4 h-4" />;
      case 'urgent':
        return <FireIcon className="w-4 h-4" />;
      default:
        return null;
    }
  };

  const messageTypes: { type: MessageType; label: string; color: string; description: string }[] = [
    { type: 'normal', label: 'Normal', color: MessageColors.normal, description: 'Regular message' },
    { type: 'important', label: 'Important', color: MessageColors.important, description: 'Important message' },
    { type: 'urgent', label: 'Urgent', color: MessageColors.urgent, description: 'Urgent message' },
  ];

  return (
    <div className="border-t border-gray-200 bg-white p-4">
      <form onSubmit={handleSubmit} className="space-y-3">
        {/* Message type selector */}
        <div className="relative">
          <button
            type="button"
            onClick={() => setShowTypePicker(!showTypePicker)}
            className={`
              flex items-center space-x-2 px-3 py-2 rounded-lg border transition-colors
              ${messageType === 'normal' 
                ? 'border-gray-300 bg-gray-50 hover:bg-gray-100' 
                : `border-2 hover:opacity-80`
              }
            `}
            style={{ 
              borderColor: messageType !== 'normal' ? MessageColors[messageType] : undefined,
              backgroundColor: messageType !== 'normal' ? `${MessageColors[messageType]}15` : undefined 
            }}
          >
            {getTypeIcon(messageType)}
            <span className="text-sm font-medium" style={{ color: MessageColors[messageType] }}>
              {MessageTypeLabels[messageType]}
            </span>
            <svg className={`w-4 h-4 transition-transform ${showTypePicker ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>

          {/* Type picker dropdown */}
          {showTypePicker && (
            <div className="absolute bottom-full left-0 mb-2 w-64 bg-white rounded-lg shadow-lg border border-gray-200 z-10">
              <div className="p-2">
                {messageTypes.map((type) => (
                  <button
                    key={type.type}
                    type="button"
                    onClick={() => {
                      setMessageType(type.type);
                      setShowTypePicker(false);
                    }}
                    className={`
                      w-full flex items-center space-x-3 px-3 py-2 rounded-md hover:bg-gray-50 transition-colors
                      ${messageType === type.type ? 'bg-gray-100' : ''}
                    `}
                  >
                    <div 
                      className="w-3 h-3 rounded-full" 
                      style={{ backgroundColor: type.color }}
                    />
                    {getTypeIcon(type.type)}
                    <div className="flex-1 text-left">
                      <div className="font-medium text-sm">{type.label}</div>
                      <div className="text-xs text-gray-500">{type.description}</div>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Message input */}
        <div className="flex items-end space-x-3">
          <div className="flex-1 relative">
            <textarea
              ref={textareaRef}
              value={message}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              placeholder="Type your message... (Press Enter to send, Shift+Enter for new line)"
              disabled={disabled}
              className="w-full px-4 py-3 pr-16 border border-gray-300 rounded-2xl focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent resize-none placeholder-gray-400 disabled:bg-gray-100 disabled:cursor-not-allowed"
              rows={1}
              maxLength={500}
            />
            
            {/* Character count */}
            <div className="absolute bottom-2 right-4 text-xs text-gray-400">
              {message.length}/500
            </div>
          </div>

          {/* Send button */}
          <button
            type="submit"
            disabled={!message.trim() || disabled}
            className="flex-shrink-0 bg-green-600 hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white p-3 rounded-full transition-colors duration-200"
          >
            <PaperAirplaneIcon className="w-5 h-5" />
          </button>
        </div>

        {/* Message type indicator */}
        {messageType !== 'normal' && (
          <div className="flex items-center space-x-2 text-sm">
            <span className="text-gray-600">Sending as:</span>
            <div className="flex items-center space-x-1" style={{ color: MessageColors[messageType] }}>
              {getTypeIcon(messageType)}
              <span className="font-medium">{MessageTypeLabels[messageType]}</span>
            </div>
          </div>
        )}
      </form>
    </div>
  );
}

// frontend/svelte/miniTalk/src/lib/components/MessageInput.svelte
<script lang="ts">
  import { selectedMessageType } from '../stores';
  import type { MessageType } from '../types';

  export let onSendMessage: (content: string, type: MessageType) => void;
  export let onTyping: () => void;
  export let onStopTyping: () => void;
  export let disabled = false;

  let messageInput = '';
  let typingTimeout: number | null = null;

  const messageTypes: { value: MessageType; label: string; icon: string; color: string }[] = [
    { value: 'normal', label: 'Normal', icon: '💬', color: 'from-blue-500 to-blue-600' },
    { value: 'important', label: 'Important', icon: '⚠️', color: 'from-yellow-500 to-orange-500' },
    { value: 'urgent', label: 'Urgent', icon: '🚨', color: 'from-red-500 to-red-600' },
  ];

  function handleSubmit() {
    const content = messageInput.trim();
    if (!content || disabled) return;

    onSendMessage(content, $selectedMessageType);
    messageInput = '';
    handleStopTyping();
  }

  function handleInput() {
    onTyping();
    
    if (typingTimeout) {
      clearTimeout(typingTimeout);
    }
    
    typingTimeout = setTimeout(() => {
      handleStopTyping();
    }, 1000);
  }

  function handleStopTyping() {
    if (typingTimeout) {
      clearTimeout(typingTimeout);
      typingTimeout = null;
    }
    onStopTyping();
  }

  function handleKeyPress(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      handleSubmit();
    }
  }
</script>

<div class="glass-input-container p-6 border-t border-white/10">
  <!-- Message Type Selector -->
  <div class="flex flex-wrap gap-2 mb-4">
    {#each messageTypes as type}
      <button
        on:click={() => selectedMessageType.set(type.value)}
        class="
          px-4 py-2 rounded-2xl border transition-all duration-300 
          text-sm font-semibold flex items-center space-x-2
          {$selectedMessageType === type.value 
            ? `bg-gradient-to-r ${type.color} text-white border-transparent shadow-lg scale-105` 
            : 'glass-type-btn text-white/80 border-white/20 hover:border-white/40 hover:bg-white/10'
          }
        "
        disabled={disabled}
      >
        <span>{type.icon}</span>
        <span>{type.label}</span>
        {#if $selectedMessageType === type.value}
          <div class="w-2 h-2 bg-white rounded-full animate-pulse" />
        {/if}
      </button>
    {/each}
  </div>

  <!-- Message Input Form -->
  <form on:submit|preventDefault={handleSubmit} class="space-y-4">
    <div class="flex space-x-4">
      <!-- Message Input -->
      <div class="flex-1 relative">
        <textarea
          bind:value={messageInput}
          on:input={handleInput}
          on:keydown={handleKeyPress}
          on:blur={handleStopTyping}
          placeholder="Tapez votre message..."
          maxlength="500"
          rows="1"
          class="
            w-full px-6 py-4 rounded-2xl glass-input
            text-white placeholder-white/50 
            border border-white/20 
            focus:border-blue-400/50 focus:ring-2 focus:ring-blue-400/20
            transition-all duration-300
            resize-none overflow-hidden
            text-base leading-relaxed
          "
          style="min-height: 56px; max-height: 120px;"
          {disabled}
        />
        
        <!-- Character Counter -->
        <div class="absolute bottom-2 right-4 text-xs text-white/50 font-medium">
          {messageInput.length}/500
        </div>
      </div>

      <!-- Send Button -->
      <button
        type="submit"
        disabled={disabled || !messageInput.trim()}
        class="
          px-8 py-4 rounded-2xl font-bold text-white
          bg-gradient-to-r from-blue-500 to-indigo-600
          hover:from-blue-400 hover:to-indigo-500
          disabled:from-gray-600 disabled:to-gray-700
          shadow-lg transition-all duration-300 transform
          hover:scale-105 hover:shadow-2xl
          disabled:scale-100 disabled:shadow-none disabled:cursor-not-allowed
          relative overflow-hidden group
          flex items-center space-x-2 min-w-[120px] justify-center
        "
      >
        {#if disabled}
          <div class="flex items-center space-x-2">
            <div class="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            <span>Envoi...</span>
          </div>
        {:else}
          <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
          </svg>
          <span>Envoyer</span>
        {/if}
        
        <!-- Shine effect on hover -->
        <div class="absolute inset-0 bg-gradient-to-r from-white/0 via-white/20 to-white/0 -translate-x-full transition-transform duration-700 group-hover:translate-x-full" />
      </button>
    </div>

    <!-- Input Footer -->
    <div class="flex items-center justify-between text-sm text-white/60">
      <div class="flex items-center space-x-4">
        <div class="flex items-center space-x-2">
          <div class="w-2 h-2 bg-blue-400 rounded-full animate-pulse" />
          <span>Appuyez sur Entrée pour envoyer</span>
        </div>
        
        {#if $selectedMessageType !== 'normal'}
          <div class="flex items-center space-x-2 px-3 py-1 rounded-full glass-badge">
            <span class="text-xs">Type sélectionné:</span>
            <span class="font-semibold text-white/80">
              {messageTypes.find(t => t.value === $selectedMessageType)?.label}
            </span>
          </div>
        {/if}
      </div>
      
      <div class="flex items-center space-x-2">
        {#if disabled}
          <div class="text-red-400 font-medium">Hors ligne</div>
        {:else}
          <div class="text-green-400 font-medium">En ligne</div>
        {/if}
      </div>
    </div>
  </form>
</div>

<style>
  .glass-input-container {
    background: rgba(255, 255, 255, 0.05);
    backdrop-filter: blur(20px);
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  .glass-input {
    background: rgba(255, 255, 255, 0.08);
    backdrop-filter: blur(15px);
  }

  .glass-input:focus {
    background: rgba(255, 255, 255, 0.12);
  }

  .glass-type-btn {
    background: rgba(255, 255, 255, 0.05);
    backdrop-filter: blur(10px);
  }

  .glass-badge {
    background: rgba(255, 255, 255, 0.1);
    backdrop-filter: blur(5px);
  }

  /* Auto-resize textarea */
  textarea {
    field-sizing: content;
  }
</style>
